nginx:
  image: tutum/nginx
  ports:
    - "80:80"
  volumes:
    - ./public_html:/code
    - ./sites-available/default:/etc/nginx/sites-available/default
    - ./sites-available/default:/etc/nginx/sites-enabled/default

    - ./logs/nginx-error.log:/var/log/nginx/error.log
    - ./logs/nginx-access.log:/var/log/nginx/access.log
  links:
        - phpfpm
phpfpm:
  image: php:fpm
  volumes:
    - ./public_html:/code
mysql:
  image: mariadb
  volumes:
    - /var/lib/mysql
    - ./backup:/backup
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
